
CREATE TABLE [NhanVien] (
	[Mnv] NVARCHAR(255) NOT NULL UNIQUE,
	[Sdt] NVARCHAR(255) NOT NULL,
	[SinhNhat] DATE NOT NULL,
	[DiaChi] NVARCHAR(255) NOT NULL,
	[HoTen] NVARCHAR(255) NOT NULL,
	[GioiTinh] NVARCHAR(255) DEFAULT 'Nam',
	[ChucVu] NVARCHAR(255) NOT NULL DEFAULT 'NhanVienQuay',
	[Luong] FLOAT NOT NULL DEFAULT 7000000,
	PRIMARY KEY([Mnv])
);
GO

CREATE TABLE [SanPham] (
	[Msp] NVARCHAR(255) NOT NULL UNIQUE,
	[Mncc] NVARCHAR(255) NOT NULL UNIQUE,
	[TenSp] NVARCHAR(255) NOT NULL,
	[SoLuong] INT NOT NULL,
	[Gia] FLOAT NOT NULL,
	[NgayNhap] DATE NOT NULL,
	[HetHan] DATE NOT NULL,
	[HetHang] BIT NOT NULL DEFAULT False,
	PRIMARY KEY([Msp])
);
GO

CREATE INDEX [_index]
ON [SanPham] ();
GO

CREATE TABLE [NhaCungCap] (
	[Mncc] NVARCHAR(255) NOT NULL UNIQUE,
	[Ten] NVARCHAR(255) NOT NULL,
	[DiaChi] NVARCHAR(255) NOT NULL,
	[Sdt] NVARCHAR(255) NOT NULL,
	[HopTac] BIT NOT NULL DEFAULT True,
	PRIMARY KEY([Mncc])
);
GO

CREATE TABLE [KhachHang] (
	[Mkh] NVARCHAR(255) NOT NULL UNIQUE,
	[HoTen] NVARCHAR(255) NOT NULL,
	[DiaChi] NVARCHAR(255) NOT NULL,
	[Sdt] NVARCHAR(255) NOT NULL,
	-- neu sai la khach thuong, dung la khach vip
	[HangKhach] BIT NOT NULL DEFAULT False,
	PRIMARY KEY([Mkh])
);
GO

CREATE TABLE [UuDai] (
	[Mud] NVARCHAR(255) NOT NULL UNIQUE,
	[Mkh] NVARCHAR(255) NOT NULL,
	[Ten] NVARCHAR(255) NOT NULL,
	PRIMARY KEY([Mud])
);
GO

CREATE TABLE [HoaDon] (
	[Mhd] NVARCHAR(255) NOT NULL UNIQUE,
	[NgayXuat] DATETIME NOT NULL,
	[Msp] NVARCHAR(255) NOT NULL,
	[Tensp] NVARCHAR(255) NOT NULL,
	[SoLuong] INT NOT NULL,
	[DonGia] FLOAT NOT NULL,
	[ThanhTien] FLOAT NOT NULL,
	[Mkh] NVARCHAR(255) NOT NULL,
	[Mnv] NVARCHAR(255) NOT NULL,
	PRIMARY KEY([Mhd])
);
GO

ALTER TABLE [SanPham]
ADD FOREIGN KEY([Msp]) REFERENCES [NhaCungCap]([Mncc])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [UuDai]
ADD FOREIGN KEY([Mkh]) REFERENCES [KhachHang]([Mkh])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [HoaDon]
ADD FOREIGN KEY([Msp]) REFERENCES [SanPham]([Msp])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [HoaDon]
ADD FOREIGN KEY([Mkh]) REFERENCES [KhachHang]([Mkh])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [HoaDon]
ADD FOREIGN KEY([Mnv]) REFERENCES [NhanVien]([Mnv])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO