CREATE TABLE SanPham (
    Msp NVARCHAR(255) NOT NULL PRIMARY KEY,
    Mncc NVARCHAR(255) NOT NULL,
    TenSp NVARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,
    Gia FLOAT NOT NULL,
    NgayNhap DATE NOT NULL,
    HetHan DATE NOT NULL,
    HetHang BIT NOT NULL DEFAULT 0,
    PhanLoai NVARCHAR(255)
);

CREATE TABLE NhaCungCap (
    Mncc NVARCHAR(255) NOT NULL PRIMARY KEY,
    Ten NVARCHAR(255) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    Sdt NVARCHAR(255) NOT NULL,
    HopTac BIT NOT NULL DEFAULT 1
);

CREATE TABLE KhachHang (
    Mkh NVARCHAR(255) NOT NULL PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    Sdt NVARCHAR(255) NOT NULL,
    HangKhach BIT NOT NULL DEFAULT 0
);

CREATE TABLE UuDai (
    Mud NVARCHAR(255) NOT NULL PRIMARY KEY,
    Mkh NVARCHAR(255) NOT NULL,
    Ten NVARCHAR(255) NOT NULL
);

CREATE TABLE HoaDon (
    Mhd NVARCHAR(255) NOT NULL PRIMARY KEY,
    NgayXuat DATETIME NOT NULL,
    Msp NVARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia FLOAT NOT NULL,
    ThanhTien FLOAT NOT NULL,
    Mkh NVARCHAR(255) NOT NULL,
    Mnv NVARCHAR(255) NOT NULL
);

CREATE TABLE KhoNX (
    Mnx NVARCHAR(255) NOT NULL PRIMARY KEY,
    Msp NVARCHAR(255) NOT NULL,
    Mncc NVARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,
    TongGia FLOAT NOT NULL
);

CREATE TABLE NganSach (
    Mns NVARCHAR(255) NOT NULL PRIMARY KEY,
    Ten NVARCHAR(255) NOT NULL,
    Tien FLOAT NOT NULL,
    Mhd NVARCHAR(255),
    Msp NVARCHAR(255),
    TienNS FLOAT NOT NULL,
    Mnx NVARCHAR(255)
);

CREATE TABLE NhanVien (
    Mnv NVARCHAR(255) NOT NULL PRIMARY KEY,
    Sdt NVARCHAR(255) NOT NULL,
    SinhNhat DATE NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    HoTen NVARCHAR(255) NOT NULL,
    GioiTinh NVARCHAR(255) NOT NULL DEFAULT 'Nam',
    ChucVu NVARCHAR(255) NOT NULL,
    Luong FLOAT NOT NULL DEFAULT 7000000
);

CREATE TABLE DangNhap (
    Mdn NVARCHAR(255) NOT NULL PRIMARY KEY,
    Mnv NVARCHAR(255) NOT NULL,
    GioVao DATETIME NOT NULL,
    GioRa DATETIME NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL
);


